defaults: &defaults
  docker:
    - image: circleci/node:13.8.0
  working_directory: ~/project

version: 2.1

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run: npm i
      - save_cache:
          paths:
            - /src/node modules
          key: "npm_packages"
      - run: npm run lint

  test:
    <<: *defaults
    steps:
      - checkout
      - run: mpm i
      - restore_cache:
          keys: 
          - "npm_packages"
      - run: npm run test
  
  analyze:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys: 
          - "npm_packages"
      - run: npm audit

workflows:
  Create_a_CI_Pipeline:
    jobs:
      - build
      - test:
          requires:
            - build
      - analyze:
          requires:
            - test