defaults: &defaults
  docker:
    - image: circleci/node:13.8.0
  working_directory: ~/project

version: 2.1

jobs:
  build:
    <<: *defaults
    steps:
      - run: echo "shovon"

  test:
    <<: *defaults
    steps:
      - run: echo "shovon"   
  
  analyze:
    <<: *defaults
    steps:
      - run: echo "shovon"
workflows:
  Create_a_CI_Pipeline:
    jobs:
      - build
      - test
      - analyze